sudo: required
dist: trusty

services:
  - docker

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
    - curl

script:
 
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH  PR=$TRAVIS_PULL_REQUEST"
  - if [ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker build -t rolfwessels/docker-simple-nuget-server:latest -t rolfwessels/docker-simple-nuget-server:v1.1.$TRAVIS_BUILD_NUMBER .;
    else
    docker build -t rolfwessels/docker-simple-nuget-server:v1.1.$TRAVIS_BUILD_NUMBER-develop .;
    fi
 
after_success:
  - popd
  - if [ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    docker push rolfwessels/docker-simple-nuget-server
    fi